language: java

addons:
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java9-installer

jdk:
  - oraclejdk8
  - oraclejdk9

notifications:
  email: false

sudo: false
cache:
  directories:
    - $HOME/.m2
